import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Ids come from the file names under the library's `docs/`. Docusaurus strips the `00-` style number prefix, so
// `docs/00-guardrails-overview.md` is `guardrails-overview` here.
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guardrails-overview' },
      items: [
        'guardrails-overview',
        'invariant-guard-matrix',
        'lint-rules',
        'boundaries-and-config',
        'hooks-and-ci',
        'consumer-api',
        'row-source-updates',
        'plugin-authoring',
        'a-bar-is-an-entry',
        'integration-pitfalls',
        'edit-extension-flow',
      ],
    },
  ],

  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],

  adrSidebar: [
    {
      type: 'autogenerated',
      dirName: 'adr',
    },
  ],
};

export default sidebars;
