import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// TypeDoc writes the pages under `website/docs/api`, so the whole instance is one autogenerated
// section. Nothing here is authored.
const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
